# Project: exvm_x64_ft

BIN      = bin/exvm_x64_ft
CXXFLAGS = -O3 -Wall -W -m64 -march=native -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations -D_VM_HOST_OS=_VM_HOST_LINUX_X64 -D_VM_INTERPRETER=_VM_INTERPRETER_FUNC_TABLE

ARCH     = x64_ft_linux

MEXT     = $(ARCH)

include interpreter.make

