# Project: exvm_mos

BIN      = bin/exvm_mos
CXX		 = ppc-morphos-g++-5
CXXFLAGS = -Ofast -Wall -W -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations -mcpu=native -noixemul -D_VM_HOST_OS=_VM_HOST_MORPHOS_PPC -D_VM_INTERPRETER=_VM_INTERPRETER_SWITCH_CASE -D__USE_BASETYPE__
LDFLAGS	 = -noixemul

ARCH     = ppc_morphos

include interpreter.make


