# Project: ExVM Multiplatform

# Target
BIN      = bin/exvm_os4_ft

# Compiler settings
CXXFLAGS = -O3 -Wall -W -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations -D_VM_HOST_OS=_VM_HOST_AMIGAOS4_PPC -D_VM_INTERPRETER=_VM_INTERPRETER_SWITCH_CASE -D__USE_BASETYPE__

# Makefile settings
ARCH     = ppc_amigaos4
MEXT     = os4_ft

include interpreter.make

