# Project: exvm_x64

BIN      = bin/exvm_x64

CXXFLAGS = -O3 -Wall -W -m64 -march=native -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations -D_VM_HOST_OS=_VM_HOST_LINUX_X64 -D_VM_INTERPRETER=_VM_INTERPRETER_SWITCH_CASE -D_GCC_USE_BUILTIN

ARCH     = x64_linux

MEXT     = $(ARCH)

include interpreter.make

