# Project: ExVM Multiplatform

# Target
BIN      = bin/exvm_x86_haiku

# Compiler settings
CXXFLAGS = -O3 -Wall -W -m32 -march=native -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations -D_VM_HOST_OS=_VM_HOST_HAIKU_X86 -D_VM_INTERPRETER=_VM_INTERPRETER_SWITCH_CASE -D_GCC_USE_BUILTIN

# Makefile settings
ARCH     = x86_haiku
MEXT     = $(ARCH)

include interpreter.make

