# Project: ExVM Multiplatform

# Target
BIN      = bin/exvm_arm64

# Compiler settings
CXXFLAGS = -O3 -Wall -W -march=native -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations -D_VM_HOST_OS=_VM_HOST_LINUX_X64 -D_VM_INTERPRETER=_VM_INTERPRETER_SWITCH_CASE

# Makefile settings
ARCH     = arm64_linux
MEXT     = $(ARCH)

include interpreter.make

