# Project: ExVM Multiplatform

# Target
BIN      = bin/exvm_os4

# Compiler settings
CXXFLAGS = -O3 -Wall -W -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations -D_VM_HOST_OS=_VM_HOST_AMIGAOS4_PPC -D_VM_INTERPRETER=_VM_INTERPRETER_SWITCH_CASE -D__USE_BASETYPE__
CC       = ppc-amigaos-gcc
CXX      = ppc-amigaos-g++
LD       = ppc-amigaos-ld
AR       = ppc-amigaos-ar

# Makefile settings
ARCH     = ppc_amigaos4
MEXT     = os4-cross

include interpreter.make

