# Project: exvm_x86

BIN      = bin/exvm_x86_ft

CXXFLAGS = -O3 -Wall -W -m32 -march=native -mfpmath=sse -fomit-frame-pointer -fno-exceptions -fexpensive-optimizations -D_VM_HOST_OS=_VM_HOST_LINUX_I386 -D_VM_INTERPRETER=_VM_INTERPRETER_FUNC_TABLE

ARCH     = x86_ft_linux

MEXT     = $(ARCH)

include interpreter.make

